title: Zihad Tarafdar
email: zihad@bmpt.du.ac.bd
description: Personal space for Zihad Tarafdar
baseurl: ''
url: 'zihadt.github.io'
twitter_username: xihad
github_username: zihadt
theme: minima
collections:
  projects:
    output: true

plugins:
  - jekyll-feed
